import { readFile } from "node:fs/promises";
import path from "node:path";
import { loadConfig } from "./config.js";
import type { ReflectResult, ServiceOptions } from "./types.js";
import {
  readTextIfExists,
  relativePosix,
  timestampForFile,
  walkFiles,
  writeText,
} from "./utils.js";

interface KnowledgeGraph {
  nodes?: Array<{ id: string; title: string; path: string; type: string }>;
  edges?: Array<{ from: string; to: string }>;
}

export async function reflectWiki(
  options: ServiceOptions = {},
): Promise<ReflectResult> {
  const config = await loadConfig(options.root);
  const graphFile = path.join(config.metaDir, "knowledge_graph.json");
  let graph: KnowledgeGraph = {};
  try {
    graph = JSON.parse(await readFile(graphFile, "utf8")) as KnowledgeGraph;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  const observations: string[] = [];
  const gaps = new Set<string>();
  const markdownFiles = await walkFiles(config.wikiDir, ".md");
  const degree = new Map<string, number>();
  for (const edge of graph.edges ?? []) {
    degree.set(edge.from, (degree.get(edge.from) ?? 0) + 1);
    degree.set(edge.to, (degree.get(edge.to) ?? 0) + 1);
  }
  for (const node of graph.nodes ?? []) {
    if ((degree.get(node.id) ?? 0) === 0) {
      observations.push(`Orphan graph node: ${node.title} (${node.path})`);
      gaps.add(`Connect or validate orphan page: ${node.title}`);
    }
  }

  const positiveClaims = new Map<string, string>();
  const negativeClaims = new Map<string, string>();
  for (const file of markdownFiles) {
    const content = await readFile(file, "utf8");
    const body = content.replace(/^---[\s\S]*?---/, "").trim();
    const relative = relativePosix(config.root, file);
    if (body.length < 180 && !/index\.md$|log\.md$/i.test(file)) {
      observations.push(
        `Thin page heuristic: ${relative} has ${body.length} characters.`,
      );
      gaps.add(`Expand evidence for thin page: ${relative}`);
    }
    if (!content.includes('generated: "true"')) {
      const claimLines = body
        .split(/\n+/)
        .map((line) => line.trim())
        .filter((line) => /^[A-Z][^#*-]{20,}[.!]$/.test(line));
      for (const claim of claimLines) {
        if (!/\[[^\]]+]\([^)]+\)|\[\[[^\]]+]]|https?:\/\//.test(claim)) {
          observations.push(
            `Unsupported-claim heuristic: ${relative}: ${claim.slice(0, 120)}`,
          );
          gaps.add(`Find evidence for an uncited claim in: ${relative}`);
        }
        const positive = claim.match(/^(.{3,60}?)\s+(?:is|are)\s+(.+)$/i);
        const negative = claim.match(/^(.{3,60}?)\s+(?:is|are)\s+not\s+(.+)$/i);
        if (negative) negativeClaims.set(negative[1]!.toLowerCase(), relative);
        else if (positive)
          positiveClaims.set(positive[1]!.toLowerCase(), relative);
      }
    }
  }
  for (const [subject, positivePath] of positiveClaims) {
    const negativePath = negativeClaims.get(subject);
    if (negativePath) {
      observations.push(
        `Possible contradiction heuristic for "${subject}" between ${positivePath} and ${negativePath}.`,
      );
      gaps.add(`Review possible contradiction about: ${subject}`);
    }
  }
  if (!observations.length)
    observations.push(
      "No thin coverage, orphan, unsupported-claim, or contradiction signals were detected.",
    );
  if (!gaps.size)
    gaps.add("No heuristic gaps detected; review coverage manually.");
  const now = (options.now ?? (() => new Date()))();
  const reflectionPath = path.join(
    config.metaDir,
    "reflection",
    `${timestampForFile(now)}.md`,
  );
  const gapList = [...gaps].sort();
  await writeText(
    reflectionPath,
    `# Heuristic knowledge reflection

Generated: ${now.toISOString()}

These observations are produced by deterministic structural and lexical heuristics. They are leads for human or agent review, not verified semantic conclusions.

## Observations

${observations.map((item) => `- ${item}`).join("\n")}

## Suggested learning plan

${gapList.map((item) => `- ${item}`).join("\n")}`,
  );
  const gapsPath = path.join(config.metaDir, "gaps.md");
  await writeText(
    gapsPath,
    `# Knowledge gaps and learning plan

Generated by transparent structural/lexical heuristics; these are not verified factual gaps.

${gapList.map((item) => `- ${item}`).join("\n")}`,
  );
  const evolutionPath = path.join(config.metaDir, "evolution_log.md");
  const evolution =
    (await readTextIfExists(evolutionPath)) ?? "# Evolution log\n";
  await writeText(
    evolutionPath,
    `${evolution.trimEnd()}

- ${now.toISOString()}: reflection observations=${observations.length}, gaps=${gapList.length}, artifact=${relativePosix(config.root, reflectionPath)}`,
  );
  return { reflectionPath, gapsPath, gaps: gapList, observations };
}
